command_timeout = 5000
add_newline = true
scan_timeout = 10

format = """
[â”Œ](fg:#fff1cf)$username$directory$git_branch $all$fill$git_status$git_commit $shell$character
[â””â”€>](fg:#fff1cf) """

[line_break]
disabled = true

[fill]
symbol = " "

[character]
success_symbol = "[ï˜](cyan)"
error_symbol = "[ï±](red)"

[git_branch]
format = "$symbol$branch"
symbol = "îœ¥ "

[git_commit]
commit_hash_length = 4

[shell]
fish_indicator = "Fish"
zsh_indicator = "Zsh"
style = "dimmed"
disabled = false

[directory]
format = "[$path ](fg:#fff1cf)"
truncation_symbol = "â€¦/"
truncate_to_repo = true
truncation_length = 50

[git_status]
format = '\[$all_status$ahead_behind\]'
up_to_date = "âœ“"
staged = '[++\($count\)](green)'

[java]
symbol = "ğŸ’©â€‰"

[username]
format = "[ ï§  ](fg:#fff1cf bold)"
show_always = true
disabled = false
