command_timeout = 5000
add_newline = true
scan_timeout = 10

format = """
[â”Œ]()$username$directory$git_branch $all$fill$git_status$git_commit $shell$character
[â””â”€>]() """

[line_break]
disabled = true

[fill]
symbol = " "

[character]
success_symbol = "[ï˜](cyan)"
error_symbol = "[ï±](red)"

[git_branch]
format = "$symbol$branch"
symbol = "îœ¥ "

[git_commit]
commit_hash_length = 4

[shell]
fish_indicator = "Fish"
zsh_indicator = "Zsh"
nu_indicator = "ï¬¦ Nu"
style = "dimmed"
disabled = false

[directory]
format = "[$path ]()"
truncation_symbol = "â€¦/"
truncate_to_repo = true
truncation_length = 50

[git_status]
format = '\[$all_status$ahead_behind\]'
up_to_date = "âœ“"
staged = '[++\($count\)](green)'

[java]
symbol = "ğŸ’©â€‰"

[username]
format = "[ ï§  ]()"
show_always = true
disabled = false
